import "./globals.css";
import Topo from "../componentes/Topo";
import Rodape from "../componentes/Rodape";
import Script from "next/script";

export const metadata = {
  title: "Projeto Prevenus",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <head>
        {/* Google Tag Manager */}
        <Script
          id="google-tag-manager"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
              (function(w,d,s,l,i){
                w[l]=w[l]||[];
                w[l].push({'gtm.start': new Date().getTime(),event:'gtm.js'});
                var f=d.getElementsByTagName(s)[0],
                j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';
                j.async=true;
                j.src='https://www.googletagmanager.com/gtm.js?id=' + i + dl;
                f.parentNode.insertBefore(j,f);
              })(window,document,'script','dataLayer','G-C954W9XDEG');
            `,
          }}
        />
        {/* End Google Tag Manager */}

        <link rel="icon" href="/favicon.ico" type="image/x-icon" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Projeto Prevenus" />
        <meta name="keywords" content="Prevenus, alongamentos, saúde, ergonomia" />
        <meta name="author" content="ihbrazil Full Stack developers" />
        <meta property="og:description" content="Projeto Prevenus - Prevenção de Doenças Ocupacionais em Informática" />
      </head>
      <body>
        {/* Google Tag Manager (noscript) */}
        <noscript>
          <iframe
            src="https://www.googletagmanager.com/ns.html?id=G-C954W9XDEG"
            height="0"
            width="0"
            style={{display:'none', visibility:'hidden'}}
          ></iframe>
        </noscript>
        {/* End Google Tag Manager (noscript) */}
        <Topo/>
        {children}
        <Rodape/>
      </body>
    </html>
  );
}